Repository oblador/react-native-collapsible, pull requests merged in 2018-10, with the labels that each got.

#216 Handle collapsible unmount during animation
  Collapsible.js
Labels: bug-fix

#224 Ensure node version is compatible with eslint + nvmrc
  .nvmrc
  package.json
Labels: enhancement

#253 1.2.1
  package.json
Labels: RELEASE

#257 Remove Accordion.handleErrors
  Accordion.js
Labels: enhancement

#258 Improved type definition for Accordion.d.ts
  Accordion.d.ts
Labels: enhancement

#259 1.3.0
  Accordion.d.ts
  Accordion.js
  package.json
Labels: RELEASE
