Repository oblador/react-native-collapsible, pull requests merged in 2018-04, with the labels that each got.

#166 (Accordion) - Add expandFromBottom prop
  Accordion.js
Labels: enhancement

#147 fix: measure content height on layout change
  Collapsible.js
Labels: bug-fix

#155 0.11.0
  Accordion.js
  Collapsible.js
  Example/.babelrc
  Example/.flowconfig
  Example/.gitignore
  Example/android/app/BUCK
  Example/android/app/build.gradle
  Example/android/app/proguard-rules.pro
  Example/android/app/src/main/AndroidManifest.xml
  Example/android/app/src/main/java/com/example/MainApplication.java
  Example/android/build.gradle
  Example/android/gradle/wrapper/gradle-wrapper.properties
  Example/android/keystores/BUCK
  Example/app.json
  Example/iOS/Example.xcodeproj/project.pbxproj
  Example/iOS/Example/AppDelegate.m
  Example/iOS/Example/Images.xcassets/Contents.json
  Example/iOS/Example/Info.plist
  Example/iOS/ExampleTests/ExampleTests.m
  Example/index.ios.js
  Example/index.js
  Example/package.json
  Example/rn-cli.config.js
  Example/yarn.lock
  README.md
  index.d.ts
  package.json
Labels: RELEASE

#178 0.11.2
  Collapsible.js
  package.json
Labels: RELEASE
