Repository oblador/react-native-collapsible, pull requests merged in 2019-07, with the labels that each got.

#292 Type definition for 'disabled' property
  Accordion.d.ts
Labels: bug-fix

#287 Add Footer
  Accordion.d.ts
  Accordion.js
  README.md
Labels: enhancement

#298 1.5.0
  .eslintrc
  .prettierignore
  .prettierrc
  .travis.yml
  Accordion.d.ts
  Accordion.js
  Example/App.js
  README.md
  index.d.ts
  package.json
  yarn.lock
Labels: RELEASE
